version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: web-app-backend
    ports:
      - "81:81"
    volumes:
      - recipe-db-data:/app
    restart: always

  frontend:
    build: 
        context: ./frontend/react-frontend
        dockerfile: Dockerfile
    image: web-app-frontend

    ports:
      - "3000:80"
    restart: always

volumes:
  recipe-db-data:
    driver: local
